kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myspringbootapp
  template:
    metadata:
      labels:
        editor: vscode
        app: myspringbootapp
    spec:
      containers:
        - name: myspringbootapp
          image: marcmael/counter-java-webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9099
